spring:
  application:
    name: Nemozone
  datasource:
    url: jdbc:h2:tcp://localhost/~/nemozone
    username: sa
    password: qwer
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: api-docs
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true
  packages-to-scan: Nemozone.Nemozone
  paths-to-match: /**

kakao:
  client-id: 985c338e6200bfd6ef604e08c2d6475b
  redirect-uri: http://localhost:8080/login/kakao/callback